name: CI Pipeline

on:
  push:
    branches: [ main ]        # Ejecuta el pipeline autom치ticamente cuando hay cambios en la rama 'main'
  pull_request:
    branches: [ main ]        # Ejecuta el pipeline cuando se abre un Pull Request hacia 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest    # Usa una m치quina virtual Ubuntu como agente de ejecuci칩n

    steps:
      # Descarga el c칩digo fuente del repositorio
      - uses: actions/checkout@v4

      - name: Cachear paquetes NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      # Instala el SDK de .NET 8.x en el agente
      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'   
      
      - name: Restaurar dependencias
        run: dotnet restore

      # Compila el proyecto en modo Release
      - name: Compilar
        run: dotnet build --configuration Release

      # Ejecuta las pruebas del proyecto (sin recompilar)
      - name: Ejecutar pruebas
        run: dotnet test --configuration Release --no-build